# Generated by Django 3.0.4 on 2020-03-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
